<?php

/**
*
* @package xbtBB3cker
* @copyright (c) 2015 PPK
* @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*
*
*/

if (!defined('IN_PHPBB'))
{
	exit;
}
if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	// common
	'PPK_TRACKER' => 'Tracciatore' , 
	'TRACKER_ANNOUNCE_URL' => 'Annuncio URL del tracker' , 
	'ATTACHMENTS_TORRENT' => 'Torrent' , 
	'ATTACHMENTS_FILE' => 'File' , 
	'ATTACHMENTS_POSTER' => 'Poster' , 
	'ATTACHMENTS_SCREENSHOT' => 'Screenshot' , 
	'TORRENT_CREATED_FOR' => 'Torrent creato per' , 
	'TORRENT_LEECHERS' => 'Sanguisughe' , 
	'TORRENT_SEEDERS' => 'Seminatrici' , 
	'TORRENT_COMPLETED' => 'Scaricato' , 
	'AUTHOR_TORRENT_COMPLETED' => 'Downloader' , 
	'TORRENT_REAL_LEECHERS' => 'Traccia le sanguisughe' , 
	'TORRENT_REAL_SEEDERS' => 'Seminatrici traccianti' , 
	'TORRENT_REAL_COMPLETED' => 'Scaricato dal tracker' , 
	'TORRENT_REM_LEECHERS' => 'Sanguisughe esterne' , 
	'TORRENT_REM_SEEDERS' => 'Seminatrici esterne' , 
	'TORRENT_REM_COMPLETED' => 'Scaricato da tracker esterni' , 
	'TORRENT_VIEWED' => 'Viste' , 
	'TORRENT_HEALTH' => 'Salute' , 
	'TORRENT_PERCENT' => 'Seminatrici' , 
	'TORRENT_FILES' => 'File' , 
	'TORRENT_SIZE' => 'Taglia' , 
	'TORRENT_STATUS' => 'Stato torrent' , 
	'TORRENT_ADDED' => 'Aggiunto' , 
	'TORRENT_AUTHOR' => 'Autore' , 
	'TORRENT_NAME' => 'Titolo' , 
	'VOTING_TORRENT' => 'Valutazione torrent' , 
	'VOTING_TORRENT_VALS' => array ( '5' , '4' , '3' , '2' , '1' ), 
	'MESS_MAX_TORRENTS' => 'Numero massimo di file torrent in un messaggio: %d' , 
	'MESS_MAX_POSTERS' => 'Numero massimo di poster in un messaggio: %d' , 
	'MESS_MAX_SCREENSHOTS' => 'Numero massimo di screenshot in un messaggio: %d' , 
	'MESS_MIN_TORRENTS' => 'Numero minimo di file torrent in un messaggio: %d' , 
	'MESS_MIN_POSTERS' => 'Numero minimo di poster in un messaggio: %d' , 
	'MESS_MIN_SCREENSHOTS' => 'Numero minimo di screenshot in un messaggio: %d' , 
	'G_UPLOADERS' => 'Uploaders' , 
	'G_VIPUPLOADERS' => 'VIP uploaders',
	'G_SUPERUPLOADERS' => 'Superuploaders',
	'G_EXPUPLOADERS' => 'Experienced uploaders',
	'G_LEECHERS' => 'Leechers',
	'G_EXPLEECHERS' => 'Experienced leechers',
	'G_TRUSERS' => 'Tracker visitors',
	'G_CHATUSERS' => 'Chat users',
	'G_PRIVTRUSERS' => 'Private users',
	'G_MODERATORS' => 'Moderators',
	'G_JRMODERATORS' => 'Junior Moderators',
	'DOWNLOAD_TORRENT_SHORT' => 'Download',
	'DOWNLOAD_TORRENT' => 'Download torrent',
	'DOWNLOAD_POSTER' => 'Download poster',
	'DOWNLOAD_SCREENSHOT' => 'Download screenshot',
	'DISPLAY_TORRENTS' => 'Display torrents',
	'DISPLAY_TORRENTS_ALL' => 'all',
	'DISPLAY_TORRENTS_WBAD' => 'without bad',
	'DISPLAY_TORRENTS_GOOD' => 'active',
	'DISPLAY_TORRENTS_DEAD' => 'dead',
	'DISPLAY_TORRENTS_NOSEED' => 'no seeder',
	'DISPLAY_TORRENTS_BAD' => 'bad',

	'TORRENT_INFO' => 'About torrent',

	'TORRENT_INFO_HEADER_' => '',
	'TORRENT_INFO_HEADER_A' => 'Connection',
	'TORRENT_INFO_HEADER_ACTIVE' => 'Active',
	'TORRENT_INFO_HEADER_ADDED' => 'Date',
	'TORRENT_INFO_HEADER_ADD_DATE' => 'Date',
	'TORRENT_INFO_HEADER_AGENT' => 'Client',
	'TORRENT_INFO_HEADER_ANNOUNCED' => 'Announces',
	'TORRENT_INFO_HEADER_A_INTERVAL' => 'Interval',
	'TORRENT_INFO_HEADER_A_MESSAGE' => 'Message',
	'TORRENT_INFO_HEADER_BONUSES' => 'Bonuses',
	'TORRENT_INFO_HEADER_BOOKMARKS' => 'Future downloads',
	'TORRENT_INFO_HEADER_COMPLETEDAT' => 'End',
	'TORRENT_INFO_HEADER_COND' => 'Status',
	'TORRENT_INFO_HEADER_CONDLEECH' => 'Leecher',
	'TORRENT_INFO_HEADER_CONDSEED' => 'Seeder',
	'TORRENT_INFO_HEADER_CONNECT' => 'Connection',
	'TORRENT_INFO_HEADER_CONNECTABLE' => 'Connected',
	'TORRENT_INFO_HEADER_DL_TIME' => 'Date',
	'TORRENT_INFO_HEADER_DOWNLOADED' => 'Downloaded',
	'TORRENT_INFO_HEADER_DOWNLOADS' => 'Download file',
	'TORRENT_INFO_HEADER_DOWNSPEED' => 'Speed',
	'TORRENT_INFO_HEADER_DOWNTIME' => 'Downloaded for',
	'TORRENT_INFO_HEADER_ERR_COUNT' => 'Errors',
	'TORRENT_INFO_HEADER_FILELIST' => 'List of files',
	'TORRENT_INFO_HEADER_FILENAME' => 'File',
	'TORRENT_INFO_HEADER_FINISHED' => 'Who finished',
	'TORRENT_INFO_HEADER_HISTORY' => 'History',
	'TORRENT_INFO_HEADER_INA' => 'Inaction',
	'TORRENT_INFO_HEADER_IP' => 'IP address',
	'TORRENT_INFO_HEADER_LAST_ACTION' => 'Last',
	'TORRENT_INFO_HEADER_LEAVE' => 'Leaving',
	'TORRENT_INFO_HEADER_LEECH' => 'Leeching',
	'TORRENT_INFO_HEADER_LEECHERS' => 'Leechers',
	'TORRENT_INFO_HEADER_LEFT' => 'Completed',
	'TORRENT_INFO_HEADER_MTIME' => 'Last',
	'TORRENT_INFO_HEADER_NEXT_ANNOUNCE' => 'Announce through',
	'TORRENT_INFO_HEADER_NOWSEED2' => 'Seeding',
	'TORRENT_INFO_HEADER_NOWSEED_NO' => 'No',
	'TORRENT_INFO_HEADER_NOWSEED_YES' => 'Yes',
	'TORRENT_INFO_HEADER_PERCENT' => 'Completed',
	'TORRENT_INFO_HEADER_PORT' => 'Port',
	'TORRENT_INFO_HEADER_RATIO' => 'Ratio',
	'TORRENT_INFO_HEADER_REMOTE' => 'External trackers',
	'TORRENT_INFO_HEADER_RTRACK_URL' => 'Tracker',
	'TORRENT_INFO_HEADER_SEED' => 'Seeding',
	'TORRENT_INFO_HEADER_SEEDER' => 'Seeding',
	'TORRENT_INFO_HEADER_SEEDER2' => 'Seeding',
	'TORRENT_INFO_HEADER_SEEDERS' => 'Seeders',
	'TORRENT_INFO_HEADER_SIZE' => 'Size',
	'TORRENT_INFO_HEADER_STARTDAT' => 'Start',
	'TORRENT_INFO_HEADER_TADDED' => 'Date',
	'TORRENT_INFO_HEADER_TIMES_COMPLETED' => 'Downloaded',
	'TORRENT_INFO_HEADER_TOPIC_TITLE' => 'Torrent',
	'TORRENT_INFO_HEADER_TORRENTS' => 'Torrents',
	'TORRENT_INFO_HEADER_TO_GO' => 'Completed',
	'TORRENT_INFO_HEADER_UPLOADED' => 'Uploaded',
	'TORRENT_INFO_HEADER_UPSPEED' => 'Speed',
	'TORRENT_INFO_HEADER_USERNAME' => 'User',

	'TORRENT_UNKNOWN_HEALTH' => 'unknown',
	'TORRENT_UNKNOWN_CONNECTABLE' => 'unknown',
	'TORRENT_UNKNOWN_SIZE' => 'unknown',
	'TORRENT_UNKNOWN_STATUS' => 'unknown',
	'STATUS_NO_REASON' => 'not specified',
	'TSEC' => 'sec',
	'TMIN' => 'min',
	'THOUR' => 'h',
	'TDAY' => 'd',
	'SEARCH_UNANSWERED_TORRENT' => 'Torrents without comments',
	'SEARCH_UNREAD_TORRENT' => 'Unread in torrents',
	'SEARCH_ACTIVE_TORRENT' => 'Active torrents',
	'SEARCH_ALL_TORRENT' => 'Torrents',
	'SEARCH_NEW_TORRENT' => 'New torrents',
	'SEARCH_SELF_TORRENT' => 'Your torrents',
	'SEARCH_USER_TORRENT' => 'User torrents',
	'SEARCH_ALL_COMMENT' => 'Comments',
	'SEARCH_SELF_COMMENT' => 'Your comments',
	'SEARCH_USER_COMMENT' => 'User comments',
	'SEARCH_NEW_COMMENT' => 'New comments',

	'TOTAL_TORRENT' => 'Torrents: <strong>%d</strong>',
	'TOTAL_COMMENT' => 'Comments: <strong>%d</strong>',
	'TOTAL_PEER' => 'Peers: <strong>%d</strong>',
	'TOTAL_SEED' => 'Seeds: <strong>%d</strong>',
	'TOTAL_LEECH' => 'Leechs: <strong>%d</strong>',
	'TOTAL_SEED_WR' => 'Seeders: <strong class="my_tt" title="External: %2$d">%1$d</strong>',
	'TOTAL_LEECH_WR' => 'Leechers: <strong class="my_tt" title="External: %2$d">%2$d</strong>',
	'TOTAL_COMPLET' => 'Downloaded torrents: <strong>%d</strong>',
	'TOTAL_COMPLET_WR' => 'Downloaded torrents: <strong class="my_tt" title="On external trackers: %2$d">%1$d</strong>',
	'TOTAL_REMSEED' => 'External seeders: %d',
	'TOTAL_REMLEECH' => 'External leechers: %d',
	'TOTAL_REMCOMPLET' => 'Downloaded torrents on external trackers: %d',
	'TOTAL_TORRSIZE' => 'Total torrent size: <strong>%s</strong>',
	'TOTAL_UP' => 'Total uploaded: <strong>%s</strong>',
	'TOTAL_DOWN' => 'Total downloads: <strong>%s</strong>',
	'TOTAL_SUP' => 'Created per session: <strong>%s</strong>',
	'TOTAL_SDOWN' => 'Downloaded per session: <strong>%s</strong>',
	'TOTAL_TDOWN' => 'Seeding torrents: <strong>%s</strong>',
	'TOTAL_TUP' => 'Leeching torrents: <strong>%s</strong>',
	'TOTAL_UDOWN' => 'Seeding users: <strong>%s</strong>',
	'TOTAL_UUP' => 'Leeching users: <strong>%s</strong>',
	'TOTAL_SPEEDDOWN' => 'Total download speed: <strong>%s</strong>',
	'TOTAL_SPEEDUP' => 'Total upload speed: <strong>%s</strong>',

	'TORRENT_HASH' => 'Hash',
	'DUPLICATED_PASSKEY' => 'This passkey already exists',
	'CANT_DOWN_POSTSCR' => 'You can NOT download posters and screenshots',

	'TORRENT_WAIT_NEVER' => 'It is not possible to download a torrent, it’s important to download it, you need to increase the ratio or increase the upload',

	'TORRENT_SUBJECT' => 'Torrent topic',

	'TRACKER_SEARCHED_TRACKER' => 'on the tracker',
	'TRACKER_SEARCHED_TORRENT' => 'in torrents',
	'TRACKER_SEARCHED_COMMENT' => 'in the comments',
	'TRACKER_SEARCHED_FORUM' => 'in the forum',
	'TRACKER_SEARCHED_ALL' => 'everywhere',
	'DISPLAY_RESULTS' => 'Show results as',
	'RETURN_BACK' => '<br /> <br /> <a href="%s"> Go back </a>',
	'DATA_PERIOD_SHORT' => array ('y' => 'g.', 'm' => 'month.', 'd' => 'd.', 'h' => 'hour.', 'i' => 'min.', 's' => 'sec.'),

	'PB' => 'PB',
	'PIB' => 'PB',
	'EB' => 'EB',
	'EIB' => 'EB',

	'TRACKER_USER_TORRENTS' => 'Torrents',
	'TRACKER_TOP' => 'Top %d tracker',

	'DOWNLOAD_FOR' => 'Downloaded',

	'TRGUESTS_DISABLED' => 'The guest tracker is disabled, you need to register and/or enter the tracker to download',

	'TORRENT_DELETED' => 'Torrent does not exist',
	'TORRENT_UNREGISTERED' => 'Unregistered torrent',
	'USER_DELETED' => 'User does not exist',

	'PPKBB_VERSION_UPDATED' => 'Tracker version updated',
	'USER_RATIOS' => array(), // array ('Leech.' => 'Leacher', 'Seed.' => 'Seeder', 'Inf.' => 'Beginner', 'None.' => ' No ratio '), // DO NOT use html code
	'SHOW_HIDE' => 'Show/Hide',
	'UPLOAD_TORRENT' => 'Upload torrent',

	'FEED_ALL_TORRENTS' => 'All torrents',
	'FEED_ALL_COMMENTS' => 'All comments',
	'FEED_TORRENTS' => 'Forum torrents',
	'FEED_COMMENTS' => 'Forum comments',
	'FEED_COMMENT' => 'Comments on the topic',

	'DT_SLENGTHMENU' => 'Displayed number of rows: _MENU_',
	'DT_SZERORECORDS' => 'No entries',
	'DT_SINFO' => 'Lines _START_ through _END_ (total: _TOTAL_)',
	'DT_SINFOEMTPY' => 'Lines 0 to 0 (total: 0)',
	'DT_SINFOFILTERED' => '(filtered from _MAX_ lines)',
	'DT_SSEARCH' => 'Filter:',
	'DT_SNEXT' => '>',
	'DT_SPREVIOUS' => '<',
	'DT_SFIRST' => '| <<',
	'DT_SLAST' => '>> |',
	'DT_HIDE' => 'Hide',

	'TOPDOWN_TORRENTS_ASNEWTORRENTS' => 'New torrents',
	'TOPDOWN_TORRENTS_ASNEWTORRENTS_INFORUM' => 'New torrents in the forum "%s"',
	'TOPDOWN_TORRENTS' => 'Top downloadable torrents',
	'TOPDOWN_TORRENTS_INFORUM' => 'Top downloaded torrents in the forum "%s"',
	'NO_TDT' => 'There are no suitable torrents to display',
	'TDT_WAIT' => 'Please wait, torrents are loading ..',

	'TORRENT_TOP_NOTICE' => '',
	'TORRENT_BOTTOM_NOTICE' => '',
	'TORRENT_TOP_NOTICE_GUEST' => '',
	'TORRENT_BOTTOM_NOTICE_GUEST' => '',

	'TRACKER_BOTTOM_DISCLAIMER' => 'The resource does not provide electronic versions of the works, but only collects and catalogs the links sent and published on the forum by our readers. If you are the copyright holder of any material presented and do not want the link to it to be in our catalog, contact us and we will delete it immediately. Files for sharing on the tracker are provided by users of the site, and the administration is not responsible for their content. Please do not upload files protected by copyright, as well as files of illegal content! ',
	'TRACKER_ANONYMOUS' => 'Guest',
	'TRDATA_WITHOUT_GUESTS' => 'Unregistered users (guests) are not displayed',

	'SEARCH_FULL_PHRASE' => 'Search for the entire phrase',
	'SEARCH_RESULTS_ASTOPICS' => 'Results as topics',
	'SEARCH_TITLE' => 'Title',
	'SEARCH_PHRASE' => 'Phrase',
	'SEARCH_TITLE_ONLY' => 'Only by topic name',
	'TRSEARCH_OPTIONS' => 'Options',
	'TORRENT_MAGNET_LINK' => 'Download via magnet link',
	'TORRENT_HASH_LINK' => 'Download via hash',
	'LOGORREG_DOWNLOAD' => 'To download a torrent, you must <a href="%s"> <strong> register </strong> </a> or <a href="%s"> <u> login </u> </a> to tracker ',

	'TORRENT_UPLOAD_ERRORS' => 'Error uploading torrent (%d)',
	'TORRENT_ERROR_PRIVATE' => 'The downloaded torrent is private, only NOT private torrents are allowed to be downloaded',
	'TORRENT_ERROR_NONPRIVATE' => 'Downloadable torrent is NOT private, only private torrents are allowed to download',
	'TORRENT_UPLOAD_ERROR' => 'Error uploading torrent, this torrent already <a class="postlink" href="%s"> exists </a>, message approved: <span style="color:#FF0000">%s</span>, torrent status: <strong>%s</strong> ',

	'TRACKER_STATISTICS' => 'Tracker',
	'STAT_UPDATE_INTERVAL' => 'Statistics update interval (in minutes): %d',
	'TORRENTS_COUNT' => 'Torrents',

	'USER_RESTRICTS_HEADER' => 'Warning',
	'USER_RESTRICTS_EXPLAIN' => 'Due to the low value of the ratio, the uploaded or the high value of the downloaded (%s), restrictions were automatically applied to you (<em> period for rechecking the limits of %s </em>): <br />',
	'USER_RESTRICTS_RATIO' => 'ratio less than %s',
	'USER_RESTRICTS_RATIO_TEXT' => 'ratio is %s',
	'USER_RESTRICTS_UPLOAD' => 'less than %s uploaded',
	'USER_RESTRICTS_DOWNLOAD' => 'downloaded more than %s',
	'USER_RESTRICTS_LEECH' => 'You can seeding torrents, but <strong> cannot download </strong> <br />',
	'USER_RESTRICTS_WAIT' => 'Waiting time to download torrents %2$s: <strong>%1$s</strong> <br />',
	'USER_RESTRICTS_INCLUDE' => '(including torrent files)',
	'USER_RESTRICTS_PEERS' => 'Maximum number of simultaneous connections: <strong>%d</strong> <br />',
	'USER_RESTRICTS_TORRENTS' => 'Maximum number of torrents for simultaneous downloading: <strong>%d</strong> <br />',
	'USER_RESTRICTS_DAYS' => 'The maximum number of torrents of files to download per day: <strong>%d</strong> <br />',

	'FUNCTION_DISABLED' => 'Function disabled',
	'TORRENT_FINISHED' => 'Finished',
	'TRACKER_PAGE' => 'Page',
	'MUA_ALL' => 'All',

	'BOOKMARKS_TITLE' => 'Future downloads',

	// rss
	'TRFEED' => 'Tracker channel',
	'ALL_TRACKERS' => 'All trackers',
	'FEED_TORRENTS_NEW' => 'New torrents',
	'FEED_TORRENTS_ACTIVE' => 'Active torrents',
	'TRFEED_OVERALL' => 'Torrents and comments',
	'TRACKER_TORRENTS' => 'Torrents',
	'TRACKER_COMMENTS' => 'Comments',



	// posting
	'VIEW_TORRENT' => '%s<b> Download </b>%s the torrent file uploaded to the tracker and open it in your torrent client',
	'VIEW_EDITED_TORRENT' => 'If you reloaded the torrent file %s<b> download </b>%s the torrent file uploaded to the tracker again and open it in your torrent client',

	'TRACKER_ADD_ATTACHMENT' => 'Download torrent, poster or screenshot',
	'TRACKER_ADD_ATTACHMENT_EXPLAIN' => 'The maximum allowed number of torrents: %d (%d), posters: %d (%d), screenshots %d (%d), the minimum required number in brackets',
	'UPAS_POSTER' => 'Upload as poster',
	'TRACKER_ANNWARN' => 'Delete other URL announces',
	'TRACKER_ANNWARN_EXPLAIN' => 'on the tracker, the announce of URLs contained in the uploaded torrent files is enabled, if the uploaded torrent file contains a private (personal) passkey or you do not want the torrent file to contain other announce URLs - check this option',

	'TORRENT_UPLOAD_ERRORS' => 'Error uploading torrent (%d)',
	'TORRENT_ERROR_PRIVATE' => 'The uploaded torrent is private, only NOT private torrents are allowed to upload',
	'TORRENT_ERROR_NONPRIVATE' => 'Uploadable torrent is NOT private, only private torrents are allowed to upload',

	'POSTSCR_URL_INVALID' => 'The specified image address is not valid',
	'POSTSCR_NO_SIZE' => 'Failed to determine the size of the specified image, Please enter them manually',
	'POSTSCR_WRONG_SIZE' => 'The dimensions of the specified image are %5$d×%6$d. Image sizes must be at least %1$d×%2$d, but not more than %3$d×%4$d. All dimensions are in pixels',
	'POSTSCR_WRONG_FILESIZE' => 'The weight of the specified image is %1$dbytes (%2$s). Image weight must be no more than %3$d bytes (%4$s) ',
	'POSTSCR_WHMANUAL_TITLE' => 'Manually specify image sizes',
	'POSTSCR_WIDTH' => 'Width',
	'POSTSCR_HEIGHT' => 'Height',
	'FORB_EXTPOSTSCR' => 'External posters and/or screenshots from the indicated domains are prohibited: %s',
	'FORB_EXTPOSTSCR_TRUEEXCLUDE' => 'Only external posters and/or screenshots from the indicated domains are allowed: %s',
	'EXT_POSTERS' => 'External posters',
	'EXT_SCREENSHOTS' => 'External screenshots',
	'EXT_POSTER' => 'Poster',
	'EXT_SCREENSHOT' => 'Screenshot',
	'MAX_EXT_POSTERS' => 'Maximum allowed number of external posters: %d (%d), the minimum required number is indicated in brackets',
	'MAX_EXT_SCREENSHOTS' => 'The maximum number of external screenshots allowed: %d (%d), in (brackets) the minimum required number',
	'EXTPOSTERS_REQUIRED' => 'Minimum required number of external posters: %d',
	'EXTSCREENSHOTS_REQUIRED' => 'Minimum required number of external screenshots: %d',
	'SUCCESS_BUT' => '<strong> The message was created successfully, but the following errors occurred in the process </strong>: %s, please check the message',

	'UPLOAD_TORRENT_DISABLED' => 'Page disabled',
	'UPLOAD_TORRENT_NOAUTH' => 'No forums available',

	'TORRENT_APPROVAL_NOTIFY' => '<span style="color:#FF0000; font-weight: bold;"> Your torrent will be available for download after approval by the moderator, you will be notified of the approval of your torrent </span>',

	'TRACKER_POLL_QUEST' => 'Torrent rating',
	'TRACKER_POLL_ANSW5' => 'Excellent',
	'TRACKER_POLL_ANSW4' => 'Good',
	'TRACKER_POLL_ANSW3' => 'Normal',
	'TRACKER_POLL_ANSW2' => 'Bad',
	'TRACKER_POLL_ANSW1' => 'Awful',


	//file.php
	'NOT_IN_TRACKER' => 'The torrent is not in the forum tracker',
	'NOT_TORRENT_EXTENSION' => 'The file is not a torrent',
	'CANT_DOWN_TORRENT' => 'You can NOT download torrent files',
	'CANTDOWN_TORRENT_STATUS' => 'Torrent has a status prohibiting downloading',
	'TORRENT_NOT_REGISTERED' => 'Torrent is not registered on the tracker',
	'NO_TORRENTS_IN_PM' => 'The torrent is attached in a private message, downloading is not possible',
	'MAGNET_DOWNLOADS_DISABLED' => 'Downloading through the link magnet is prohibited',
	'HASH_DOWNLOADS_DISABLED' => 'Hash downloading is not allowed',
	'TORRENT_DOWNLOADS_DISABLED' => 'Downloading through torrent files is prohibited',
	'BOTS_NOT_ALLOWED' => 'WTF bro ?!',
	'TORRENT_REQUPLOAD_ERROR' => 'Limitations on the upload, you can NOT download this torrent file, the necessary upload: %s (your: %s)',
	'TORRENT_REQRATIO_ERROR' => 'Ratio restrictions, you can NOT download this torrent file, the necessary ratio: %s (your: %s)',
	'TORRENT_REQUPRATIO_ERROR' => 'Restrictions on ratio and/or upload, you can NOT download this torrent file, necessary ratio: %s (your: %s), required upload: %s (your: %s)',
	'GUEST_DOWNLOADS_LIMIT' => 'The limit on downloading torrent files per day for guests has been exhausted, to download you need to <a href="%s"> <strong> register </strong> </a> and/or <a href="%s"> log in </a> to forum ',
	'GUEST_DOWNLOADS_IPLIMIT' => 'Exceeded the limit for downloading torrent files per day for guests from one IP address, you can not download this torrent file, try again later',
	'USER_DOWNLOADS_LIMIT' => 'The limit on downloading torrent files per day has been reached, you cannot download this torrent file, try again later',
	'USER_DOWNLOADS_IPLIMIT' => 'The limit on downloading torrent files per day from one IP address has been exhausted, you cannot download this torrent file, try again later',
	'USER_RESTRICT_DOWNLOADS_LIMIT' => 'Restriction on the number of torrent files downloaded per day (<strong>%d</strong>), you cannot download this torrent file, try again later',
	'USER_WAIT_TIME' => 'Timeout limit for downloading torrent files (<strong>%s</strong>), you cannot download this torrent file, try again later',
	'TORRENT_MAGNET_DLINK' => 'Open <a href="%1$s"> <strong> this link </strong> </a> in your torrent client',
	'TORRENT_HASH_DLINK' => 'To download the torrent, use this <strong>%s</strong> hash',
	'TRACKER_RETURN_BACK' => '<br /> <br /> <a onclick="history.back();return false;" href="#"> Go back </a> ',
	'DOWNLOAD_NOT_ALLOWED' => 'You cannot download this file',
	'TORRENT_REQUPLOAD_SIGN' => 'U',
	'TORRENT_REQRATIO_SIGN' => 'R',

	//search.php
	'ONLY_TRACKERS' => 'In the forum trackers',
	'ONLY_TRACKERS_EXPLAIN' => 'Search only in forums trackers',
	'POST_TORRENT' => 'Search',
	'POST_TORRENT_ALL' => 'Everywhere',
	'POST_TORRENT_TORRENT' => 'In torrents',
	'POST_TORRENT_COMMENT' => 'In the comments',

	'UCP_XBTBB3CKER_TRACKER_DATA' => 'Tracker',
	'UCP_XBTBB3CKER_TORRENT_DATA' => 'Torrents',
	'UCP_XBTBB3CKER_TRACKER_SETTINGS' => 'Tracker settings',
	'UCP_XBTBB3CKER_TRACKER_RTRACKURL' => 'Additional URL announce',

	// updates
	'MANUAL_UPDATE_190' => '
		<strong> Tracker update needed </strong> <br /> <br />
		1. Disable the forum <br />
		2. Back up the database <br />
		3. Copy the install directory from the /ext/ppk/xbtbb3cker/contrib/updates/ directory to the root directory of the forum <br />
		4. Launch http://tracker_address/install/install_update_1.9.0.php, click on the <u> Start update </u> link (do not refresh the page), wait for the <u> Next >> </u> link to appear, click her, wait every time her appearance and press until <u> Completed </u> <br />
		5. Delete the /install/ directory
	',

));
